[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.commerce.quotes"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "commerce", "quotes"] 
icon = "icon.png" 
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.commerce.quotes"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
